### ISSUE TITLE
Weird Safari WebUI rendering

### ISSUE THREAD

**Issue by AWare** [smartystreets/goconvey#335] opened 2015-09-03 20:44 UTC
When I open the demo tests in Safari 8.0.8, the Stories panel is not displayed when the window is large enough for the left sidebar to be shown. 

![image](https://cloud.githubusercontent.com/assets/2670496/9670471/a9a96714-5284-11e5-9018-1ca5d62b29ae.png)
And a little bigger:
![image](https://cloud.githubusercontent.com/assets/2670496/9670479/b1224e70-5284-11e5-8b87-50e926fbb069.png)

**Comment by mdwhatcott** [comment] 2015-09-03 21:58
@AWare - Yeah, we never had safari in mind when building the UI. Mainly just chrome. Probably should have noted that in the docs somewhere. Contributions welcome...

**Comment by VorT3x** [comment] 2015-09-13 15:45
@AWare I cannot reproduce this issue on Safari 8.0.8, OS X 10.10.5: http://quick.as/wYWju3rVx
Everything looks fine.

**Comment by VorT3x** [comment] 2016-03-10 12:51
@AWare any update or I'll close this issue.

**Comment by AWare** [comment] 2016-03-10 13:26
Feel free to close.

**Closed** 2016-03-10 13:27 UTC
